services:
    Netmex\Bundle\ArgumentResolver\RequestArgumentResolver:
        arguments:
            $validator: '@validator'
            $serializer: '@serializer'
        tags:
            - { name: 'controller.argument_value_resolver' }

    Netmex\Bundle\EventListener\ValidationExceptionListener:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }